### ISSUE TITLE
GLES2 depth issue

### ISSUE THREAD

**Issue by avril-gh** [gstark667/GodotTerrain#1]
There is an issue in GLES2 renderer where when reading from `DEPTH_TEXTURE` depth testing is disabled.
You can read more about it here https://github.com/godotengine/godot/issues/26703

To make this nice water shader work on GLES2, you could add workaround into `fragment shader`

```
void fragment() {
	float depth_tex = texture(DEPTH_TEXTURE, SCREEN_UV).r;
	vec4 world_pos = INV_PROJECTION_MATRIX * vec4(SCREEN_UV*2.0-1.0,depth_tex*2.0-1.0,1.0);
	world_pos.xyz/=world_pos.w;
	float depth_clip = clamp(1.0-smoothstep(world_pos.z+0.001,world_pos.z,VERTEX.z),0.0,1.0);
	ALPHA *= depth_clip;

```

**Comment by gstark667** [comment]
Thanks! I'll investigate if I can work this into the code. The shader also relies on reading the screen color buffer as well, so that may present issues too.

**Comment by avril-gh** [comment]
been testing it and i just found that, while it **works on PC**,

![water](https://user-images.githubusercontent.com/3224132/78995406-8f45dd80-7b42-11ea-80b4-79c204375de4.jpg)

**this `depth thing` does not work on mobile devices** with real GLES2 GPU ( eg. mali400 ) 

not mention that there's more problems on GLES2 mobiles, like
- shader length limit - which i solved by moving wave function directly into vertex shader (ran in loop)
- count of 16 varyings limit - solved by reorganize code alittle,

doing it on real GLES2 mobile device is challenging. you should try 😃

**Comment by gstark667** [comment]
Hey @avril-gh I think I've got a possible solution (sadly I couldn't get the refraction effect to work use to the screen_texture just being white, but the other effects are working)
![image](https://user-images.githubusercontent.com/3507130/79126269-415cef80-7d65-11ea-892e-eb49f103c74b.png)

I merged the code into master if you want to take a look. It's in a material called water_glse2.material and there's a second water object with the visibility turned off in the water scene that you can switch between (I was trying to find a way to query what render system was being used and switch between the two materials at runtime, but haven't found anything yet).

**Comment by avril-gh** [comment]
> I merged the code into master if you want to take a look (...)

@gstark31897 sure, with pleasure. Im always interested in nice code ideas

**Comment by avril-gh** [comment]
> I was trying to find a way to query what render system was being used and switch between the two materials at runtime

you'll get it by
`ProjectSettings.get_setting("rendering/quality/driver/driver_name")`

and the string to query ( _rendering/quality/driver/driver_name_ ) you'll get from hovering mouse above setting you want.

![project_settings](https://user-images.githubusercontent.com/3224132/80299410-6d7c6580-8794-11ea-956a-0a95698bc0a7.jpg)

or `OS.get_current_video_driver()` like the description reads on image above.

Ok. closing this issue to decrease issues count.
